# Generated by Django 4.0.5 on 2022-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('discription', models.CharField(max_length=20)),
                ('stock_quantity', models.IntegerField(max_length=10)),
                ('volume', models.TextField()),
            ],
        ),
    ]
